#include <stdio.h>

int main()
{
	const double GRAVITY =9.8;
	const double EFFICIENCY =0.9;
	const double WATER_DENSITY = 1000.0;

	double height, flowRate;
	double massPersecond;
	double powerWatts, powerMW;

	printf("Enter height of the dam (m): ");
	scanf("%lf", &height);



	printf("Enter flow rate of water (m^3/s): ");
	scanf("%lf", &flowRate);

	massPersecond = flowRate * WATER_DENSITY;
        powerWatts = EFFICIENCY * massPersecond * GRAVITY * height;
	powerMW = powerWatts/ 1000000.0;

	printf("Predicted power generated by the hydroelec-tric dam: %.2f megawatts\n", powerMW);

	return 0;
}
